[package]
name = "passthrough-proxy-rust"
version = "0.0.1"
edition = "2021"

[dependencies]
actix = "0.13.3"
actix-web = "4.5.1" # TODO: features
anyhow = "1.0.83"
reqwest = { version = "0.12.4", features = ["default-tls", "http2", "macos-system-configuration"] }
